### PR TITLE
[PS] Updated to use the new version of http-verbs with play-auditing …

### PR DESCRIPTION
**Pull request by beyond-code-github**
…as a seperate component

### CODE REVIEW

**Comment by xnejp03** [comment]
we are trying not to have all the dependencies in the bootstrap library. This then creates dependency hierarchy and pain to upgrade. Whoever needs the auditing library should bring it to their project.

**Comment by xnejp03** [comment]
Also, does the new version of http-verbs require us to release this as a major release? 

EDIT: I guess it will as some package names changed

**Comment by xnejp03** [comment]
oh, I just checked. Did you just rip out the auditing stuff from http-verbs basically? In that case this is probably acceptable.

**Comment by beyond-code-github** [comment]
Yes it will require a major release. And yes this is just a rip out of the existing stuff... I think even frontend-bootstrap might not compile without it!

**Comment by beyond-code-github** [comment]
Thanks Petr

**Pull request merged**
